version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master
  - develop

max_jobs: 1

image: Visual Studio 2015

platform: Any CPU

build:
  publish_wap: true
  publish_aspnet_core: true
  verbosity: minimal

